targets:
  - address: nas_host
    metrics:
      - label: system_status
        help: 'System partition status'
        oid: 1.3.6.1.4.1.6574.1.1
      - label: temperature
        help: 'Temperature of this NAS'
        oid: 1.3.6.1.4.1.6574.1.2
